# Generated by Django 2.2.6 on 2020-05-04 08:43

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique_for_date='published')),
                ('sub_title', models.CharField(max_length=200)),
                ('main_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Main photo')),
                ('thumbnail_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Thumbnail photo')),
                ('intro', models.CharField(max_length=500)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Opublikowany')], default='published', max_length=10)),
            ],
        ),
    ]
