# Generated by Django 2.2.4 on 2019-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=80, null=True, unique_for_date='published'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique_for_date='published'),
        ),
    ]
