# Generated by Django 2.2.4 on 2019-08-14 15:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190813_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
