# Generated by Django 2.2.4 on 2019-08-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='users',
            new_name='about',
        ),
    ]
