# Generated by Django 2.2.4 on 2019-08-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190820_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='about',
            new_name='about_user',
        ),
    ]
