# Generated by Django 2.2.4 on 2019-08-28 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190826_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_user',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
