# Generated by Django 2.2.4 on 2019-08-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190820_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro_user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
