# Generated by Django 2.2.4 on 2019-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
