# Generated by Django 2.2.6 on 2020-05-04 08:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, null=True, unique=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Photo')),
            ],
        ),
    ]
